<a href="https://colab.research.google.com/github/Shambhaviadhikari/PythonClass/blob/main/Music_Recommendations_(Fall_2024)37903602%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Instructions

In this assignment, we will explore practical applications of dimensionality reduction within the context of music recommendation systems.

## Dataset Info

The dataset represents audio features for a number of audio files.

  + The audio files were obtained from artists' music videos on YouTube using the `pytube` / `pytubefix` package.
  + The audio features were obtained using the `librosa` package.
  + Each YouTube video / song was split into 30-second chunks called tracks, and each row represents one of these 30-second tracks.
  + Columns ending with "mean" represent mean values, and columns ending with "var" represent variance values
  + Based on audio sampling methods used, the `track_length` is represented in units where 22050 represents one second.

More info: https://github.com/s2t2/ml-music-2023

## Part 1 - Data Loading



Load the provided dataset of audio features.

Questions:

A) Print the **shape** of the dataset. Print the number of columns. Print the number of rows.

B) In a text cell, describe the **structure** of the data - we have a "row per what?"

C) Print the **column names**.


D) Print the **number of unique songs**, as indicated by the `video_id` column (i.e. 206).

E) Print the **number of unique artists**, as indicated by the `artist_name` column (i.e. 24).

In [ ]:
from pandas import read_csv

TRACK_LENGTH = 30
N_MFCC = 13

csv_filepath = (
    "https://github.com/s2t2/ml-music-2023/raw/main/data/youtube/features_v1/"
    f"length_{TRACK_LENGTH}_mfcc_{N_MFCC}_features.csv"
)
df = read_csv(csv_filepath)
df.head()

,artist_name,video_id,audio_filename,track_number,track_length,tempo,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,...,mfcc_9_mean,mfcc_9_var,mfcc_10_mean,mfcc_10_var,mfcc_11_mean,mfcc_11_var,mfcc_12_mean,mfcc_12_var,mfcc_13_mean,mfcc_13_var
0,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,1,661500,123.046875,0.381353,0.108483,0.035173,0.000843,...,6.451812,96.068996,1.410364,101.259422,1.968380,89.808526,9.885193,85.470773,0.186532,85.876381
1,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,2,661500,117.453835,0.325079,0.095037,0.059724,0.000803,...,2.529402,163.638820,1.359641,111.545326,-0.145113,95.362841,9.985497,107.731330,0.408040,86.850819
2,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,3,661500,117.453835,0.391230,0.091207,0.062308,0.001372,...,-4.243943,77.650651,5.931900,59.565850,0.710004,56.129559,5.494471,71.811565,-2.069526,62.430867
3,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,4,661500,117.453835,0.354422,0.093518,0.070922,0.001636,...,-0.558803,111.401847,4.309566,79.829200,1.935659,77.462955,9.476080,86.830481,-2.179213,78.055285
4,frank_sinatra,LWXUdqvVO8Y,Somethin Stupid.mp4,1,661500,103.359375,0.372852,0.090570,0.078486,0.001692,...,-7.024814,67.282919,-6.018267,87.265848,-7.079118,86.895205,-1.009947,69.512053,-9.353167,55.724105

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA

In [ ]:
#A) Print the shape of the dataset. Print the number of columns. Print the number of rows.
print(f"The shape of the dataset is {df.shape}. \nIt has {df.shape[0]} rows and {df.shape[1]} columns")

The shape of the dataset is (1818, 46).
It has 1818 rows and 46 columns

B) In a text cell, describe the structure of the data - we have a "row per what?"

The dataset has 1818 rows and 46 columns. Each row represents a 30 second chunk of the full song. Therefore, we have a row per 30 second chunk per song.

In [ ]:
#C) Print the column names.
print(f"The column names are: {list(df.columns)}")

The column names are: ['artist_name', 'video_id', 'audio_filename', 'track_number', 'track_length', 'tempo', 'chroma_stft_mean', 'chroma_stft_var', 'rms_mean', 'rms_var', 'spectral_centroid_mean', 'spectral_centroid_var', 'spectral_bandwidth_mean', 'spectral_bandwidth_var', 'spectral_rolloff_mean', 'spectral_rolloff_var', 'zero_crossing_rate_mean', 'zero_crossing_rate_var', 'tonnetz_mean', 'tonnetz_var', 'mfcc_1_mean', 'mfcc_1_var', 'mfcc_2_mean', 'mfcc_2_var', 'mfcc_3_mean', 'mfcc_3_var', 'mfcc_4_mean', 'mfcc_4_var', 'mfcc_5_mean', 'mfcc_5_var', 'mfcc_6_mean', 'mfcc_6_var', 'mfcc_7_mean', 'mfcc_7_var', 'mfcc_8_mean', 'mfcc_8_var', 'mfcc_9_mean', 'mfcc_9_var', 'mfcc_10_mean', 'mfcc_10_var', 'mfcc_11_mean', 'mfcc_11_var', 'mfcc_12_mean', 'mfcc_12_var', 'mfcc_13_mean', 'mfcc_13_var']

In [ ]:
#D) Print the number of unique songs, as indicated by the video_id column (i.e. 206).
print(f"There are {df['video_id'].nunique()} songs in the dataset.")

There are 206 songs in the dataset.

In [ ]:
#E) Print the number of unique artists, as indicated by the artist_name column (i.e. 24).
print(f"There are {df['artist_name'].nunique()} artists in the dataset.")

There are 24 artists in the dataset.

## Part 2 - Artist Analysis



Investigate and explore the dataset. Use `pandas` methods. No loops allowed!

A) Rows per Artist:

  + Using `value_counts`, print the number of **rows per artist**.

> NOTE: we should have between 40 and 118 rows per artist.

B) Songs per Artist:

  + Using `groupby`, print the number of unique **songs per artist**, sorted by number of songs in descending order.
  + In a text cell, write the names of the artists who have the greatest number of songs, as well as the name of the artist who has the fewest.
  + Create a horizontal bar chart of the number of songs per artist, where the largest bars are on top. Include chart title and axis labels.

> NOTE: we should have between 6 and 12 unique songs per artist, as represented by the `video_id` .

C) Total Duration in Minutes per Artist:

  + Create a new column called `track_duration_sec` representing the track duration in seconds, and a new column called `track_duration_min` representing the track duration in minutes.
  + Using `groupby`, print the **total duration in minutes per artist**.
  + In a text cell, write the name of the artist who has the longest total duration, and the name of the artist who has the shortest.
  + Create a horizontal bar chart of the total duration in minutes per artist, where the largest bars are on top. Include chart title and axis labels.

> HINT: Divide the length by 22050 to arrive at duration in seconds (see data dictionary), and then again by 60 to arrive at duration in minutes.

> NOTE: we should have between 20 and 59 minutes of audio per artist.

D) Average Tempo per Artist:

  + Using `groupby`, print the **average tempo per artist**.
  + In a text cell, write the name of the artist who has the highest average tempo, and the name of the artist who has the lowest.
  + Create a horizontal bar chart of the average tempo per artist, where the largest bars are on top. Include chart title and axis labels.

E) Your Own Analysis:

  + Continue to explore and ask questions of the data, to better understand it.
  + Write one of your questions in a text cell, then write your own code solution to answer the question.

In [ ]:
#A) Rows per Artist:
#Using value_counts, print the number of rows per artist.
#NOTE: we should have between 40 and 118 rows per artist.

df['artist_name'].value_counts().sort_values()

artist_name
frank_sinatra         40
ac_dc                 49
andrea_bocelli        52
jason_aldean          54
john_legend           54
rihanna               63
alicia_keys           64
led_zeppelin          67
maggie_rogers         68
dr_dre                69
bach                  70
tupac                 70
adele                 74
beethoven             75
pink_floyd            83
john_mayer            83
bruce_springsteen     87
jay_z                 92
ariana_grande         92
chris_stapleton       92
coldplay              99
taylor_swift         100
john_coltrane        103
miles_davis          118
Name: count, dtype: int64

In [ ]:
#B) Songs per Artist:
# Using groupby, print the number of unique songs per artist, sorted by number of songs in descending order.
unique_artist_songs= df.groupby('artist_name')['video_id'].nunique().sort_values(ascending=False).reset_index()
unique_artist_songs

          artist_name  video_id
0        taylor_swift        12
1       ariana_grande        12
2     chris_stapleton        12
3            coldplay        12
4               jay_z        11
5          john_mayer        10
6   bruce_springsteen        10
7       maggie_rogers         9
8        jason_aldean         8
9               adele         8
10        miles_davis         8
11              tupac         8
12             dr_dre         8
13               bach         8
14        alicia_keys         8
15      frank_sinatra         7
16      john_coltrane         7
17        john_legend         7
18          beethoven         7
19       led_zeppelin         7
20     andrea_bocelli         7
21         pink_floyd         7
22            rihanna         7
23              ac_dc         6

In a text cell, write the names of the artists who have the greatest number of songs, as well as the name of the artist who has the fewest.

Artists with the greatest number of songs in the dataset(12 songs):
- Taylor Swift
- Ariana Grande
- Chris Stapleton
- Cold Play

Artist with the fewest number of songs in the dataset(6 songs):
- AC DC

In [ ]:
# Create a horizontal bar chart of the number of songs per artist, where the largest bars are on top. Include chart title and axis labels.
# NOTE: we should have between 6 and 12 unique songs per artist, as represented by the video_id .

barchart_songs = px.bar(unique_artist_songs.sort_values(by= "video_id"), x="video_id", y="artist_name",
                  orientation= "h",
                  title="Bar Chart of the Number of Songs per Artist",
                  labels={
                      'video_id': "Number of Songs",
                      'artist_name' : 'Artist Name'
                  })
barchart_songs.show()

In [ ]:
# C) Total Duration in Minutes per Artist:

# Create a new column called track_duration_sec representing the track duration in seconds, and a new column called track_duration_min representing the track duration in minutes.
df['track_duration_sec'] = df['track_length']/22050
df['track_duration_min'] = df['track_duration_sec']/60
df.head()

,artist_name,video_id,audio_filename,track_number,track_length,tempo,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,...,mfcc_10_mean,mfcc_10_var,mfcc_11_mean,mfcc_11_var,mfcc_12_mean,mfcc_12_var,mfcc_13_mean,mfcc_13_var,track_duration_sec,track_duration_min
0,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,1,661500,123.046875,0.381353,0.108483,0.035173,0.000843,...,1.410364,101.259422,1.968380,89.808526,9.885193,85.470773,0.186532,85.876381,30.0,0.5
1,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,2,661500,117.453835,0.325079,0.095037,0.059724,0.000803,...,1.359641,111.545326,-0.145113,95.362841,9.985497,107.731330,0.408040,86.850819,30.0,0.5
2,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,3,661500,117.453835,0.391230,0.091207,0.062308,0.001372,...,5.931900,59.565850,0.710004,56.129559,5.494471,71.811565,-2.069526,62.430867,30.0,0.5
3,frank_sinatra,rSrc7aulay8,Fly Me To The Moon (In Other Words).mp4,4,661500,117.453835,0.354422,0.093518,0.070922,0.001636,...,4.309566,79.829200,1.935659,77.462955,9.476080,86.830481,-2.179213,78.055285,30.0,0.5
4,frank_sinatra,LWXUdqvVO8Y,Somethin Stupid.mp4,1,661500,103.359375,0.372852,0.090570,0.078486,0.001692,...,-6.018267,87.265848,-7.079118,86.895205,-1.009947,69.512053,-9.353167,55.724105,30.0,0.5

In [ ]:
# Using groupby, print the total duration in minutes per artist.

artist_dur = df.groupby('artist_name')['track_duration_min'].sum().sort_values(ascending=False).reset_index()
artist_dur

          artist_name  track_duration_min
0         miles_davis                59.0
1       john_coltrane                51.5
2        taylor_swift                50.0
3            coldplay                49.5
4       ariana_grande                46.0
5     chris_stapleton                46.0
6               jay_z                46.0
7   bruce_springsteen                43.5
8          john_mayer                41.5
9          pink_floyd                41.5
10          beethoven                37.5
11              adele                37.0
12              tupac                35.0
13               bach                35.0
14             dr_dre                34.5
15      maggie_rogers                34.0
16       led_zeppelin                33.5
17        alicia_keys                32.0
18            rihanna                31.5
19       jason_aldean                27.0
20        john_legend                27.0
21     andrea_bocelli                26.0
22              ac_dc                24.5
23      frank_sinatra                20.0

In a text cell, write the name of the artist who has the longest total duration, and the name of the artist who has the shortest.

The artist with the longest track time is Miles Davis (59 minutes).
The artist with the the shortest track time is Frank SInatra (20 minutes).

In [ ]:
# Create a horizontal bar chart of the total duration in minutes per artist, where the largest bars are on top. Include chart title and axis labels.
# HINT: Divide the length by 22050 to arrive at duration in seconds (see data dictionary), and then again by 60 to arrive at duration in minutes.
# NOTE: we should have between 20 and 59 minutes of audio per artist.

barchart_dur = px.bar(artist_dur.sort_values(by="track_duration_min"), x='track_duration_min', y='artist_name',
                      orientation='h',
                      title = 'Bar Chart of the Total Duration (minutes) per Artist',
                      labels = {
                          'track_duration_min': 'Track Duration (min)',
                          'artist_name': 'Artist Name'
                      })
barchart_dur.show()

In [ ]:
# D) Average Tempo per Artist:
# Using groupby, print the average tempo per artist.

artist_tempo = df.groupby(['artist_name'])['tempo'].mean().reset_index().sort_values(by='tempo', ascending=False)
artist_tempo

          artist_name       tempo
13              jay_z  131.795568
6           beethoven  129.735525
14      john_coltrane  128.196795
1               adele  127.675907
4       ariana_grande  127.312845
19        miles_davis  126.816801
21            rihanna  126.761981
12       jason_aldean  126.464488
8     chris_stapleton  126.166627
9            coldplay  124.537433
20         pink_floyd  124.496634
23              tupac  122.128452
11      frank_sinatra  121.527763
16         john_mayer  121.052416
5                bach  119.993363
0               ac_dc  119.782243
22       taylor_swift  118.584689
17       led_zeppelin  117.711761
18      maggie_rogers  117.125269
15        john_legend  116.857779
7   bruce_springsteen  116.255265
3      andrea_bocelli  114.514543
2         alicia_keys  111.908552
10             dr_dre  110.993482

In a text cell, write the name of the artist who has the highest average tempo, and the name of the artist who has the lowest.

The artist with the highest average tempo is Jay Z.
The artist with the lowest everage tempo is Dr Dre.

In [ ]:
# Create a horizontal bar chart of the average tempo per artist, where the largest bars are on top. Include chart title and axis labels.

barchart_tempo = px.bar(artist_tempo.sort_values(by = 'tempo'), x='tempo', y='artist_name',
                        orientation = 'h',
                        title = 'Bar Chart of the Average Tempo per Artist',
                        labels ={
                            'tempo' : 'Average Tempo',
                            'artist_name' : 'Artist Name'
                        })
barchart_tempo.show()

E) Your Own Analysis:
Continue to explore and ask questions of the data, to better understand it.Write one of your questions in a text cell, then write your own code solution to answer the question.

Question:

- Does the data contain any null values?
- What is the duration of each audio file in the dataset? What is the average audio duration?

In [ ]:
#check for the number of missing values in the each feature of the dataset
df.isnull().sum()

artist_name                0
video_id                   0
audio_filename             0
track_number               0
track_length               0
tempo                      0
chroma_stft_mean           0
chroma_stft_var            0
rms_mean                   0
rms_var                    0
spectral_centroid_mean     0
spectral_centroid_var      0
spectral_bandwidth_mean    0
spectral_bandwidth_var     0
spectral_rolloff_mean      0
spectral_rolloff_var       0
zero_crossing_rate_mean    0
zero_crossing_rate_var     0
tonnetz_mean               0
tonnetz_var                0
mfcc_1_mean                0
mfcc_1_var                 0
mfcc_2_mean                0
mfcc_2_var                 0
mfcc_3_mean                0
mfcc_3_var                 0
mfcc_4_mean                0
mfcc_4_var                 0
mfcc_5_mean                0
mfcc_5_var                 0
mfcc_6_mean                0
mfcc_6_var                 0
mfcc_7_mean                0
mfcc_7_var                 0
mfcc_8_mean                0
mfcc_8_var                 0
mfcc_9_mean                0
mfcc_9_var                 0
mfcc_10_mean               0
mfcc_10_var                0
mfcc_11_mean               0
mfcc_11_var                0
mfcc_12_mean               0
mfcc_12_var                0
mfcc_13_mean               0
mfcc_13_var                0
track_duration_sec         0
track_duration_min         0
dtype: int64

In [ ]:
#number of tracks per song
audio_tracks = df.groupby(['audio_filename'])['track_duration_sec'].sum().reset_index().sort_values(by='track_duration_sec', ascending=False)
audio_tracks

                                        audio_filename  track_duration_sec
172         Shine On You Crazy Diamond (Parts I-V).mp4               810.0
152                             My Favorite Things.mp4               810.0
55                                      Blue Train.mp4               630.0
197  Toccata and Fugue in D Minor BWV 565 (Remaster...               540.0
149         Miles Davis - So What (Official Audio).mp4               540.0
..                                                 ...                 ...
90                                  Do You Know Me.mp4               150.0
45      Ariana Grande - positions (official video).mp4               150.0
89                                      Crossroads.mp4               120.0
96             Fly Me To The Moon (In Other Words).mp4               120.0
155  Orchestral Suite No 2 for Flute String Orchest...                90.0

[206 rows x 2 columns]

In [ ]:
import time
#average number of tracks per song
track_mean = audio_tracks['track_duration_sec'].mean()
print(f"Average Audio Duration (in minutes): {time.strftime('%M:%S', time.gmtime(track_mean))}")

Average Audio Duration (in minutes): 04:24

## Part 3 - Artist Classification


Perform artist classification using all the provided audio features.

A) X/Y Split:
  + Perform an **X/Y split**. Identify the target variable, and the feature variables.
  + Print the shape of the X and Y datasets, respectively.

B) Data Scaling:

  + **Scale the features** using a standard scaling approach.
  + Print the means and standard deviations for each column in the scaled dataset.

> FYI: all the means should be very small numbers close to zero, while all the standard deviations should be equal to one

C) Train/Test Split:

  + Perform a **train/test split** on the target and scaled features. Use 20% of the rows in the test set. Use a random state for reproducibility.
  + Print the shape of each of the resulting four datasets.

D) Model Training:

  + Using a `LogisticRegression` model from `sklearn`, **train the model** on the training data.
  + Inspect the **coefficients**. Print the shape of the coefficients.
  + In a text cell, write what the shape represents.
  + Display the coefficients as a `pandas.DataFrame`, with appropriate index values and column names.
  + Choose one of the artists, and using the coeficients, determine the top five most predictive features for that artist, and write them in a text cell.

E) Model Evaluation:

  + Evaluate the model using a **classification report**.
  + In a text cell, interpret the classification report results, and describe how well the model did. What percent accuracy represents a "random chance guess" in this particular dataset? Which artists have the highest F1 scores, and which have the lowest?
  + Display a **confusion matrix**, ideally as a heatmap with color.
  + In a text cell, write the names of the top three pairs of artists who were most confused with each other.

### X/Y Split

In [ ]:
#function for returning the X and Y datasets
def xy_split(df, target, drop_var):
    X = df.drop(columns=[*target, *drop_var])
    Y = df[target]
    print(f"X shape: {X.shape}")
    print(f"Y shape: {Y.shape}")
    return X,Y

I decided to remove the track number from the training features because it doesn't provide the model with any valuable information about the track.
I decided to remove track_duration_sec , track_duration_min, and track_length from the training features because all the tracks have the same length. This doesn't add any value to the model.
Finally, I decided the video_id and audio_filename from the training features because they are not numeric features. They are simply identifers for the audio files.

In [ ]:
# A) X/Y Split:
# Perform an X/Y split. Identify the target variable, and the feature variables.
# Print the shape of the X and Y datasets, respectively.

target = ['artist_name']
x, y = xy_split(df, target, ['video_id', 'audio_filename', 'track_number', 'track_length', 'track_duration_sec', 'track_duration_min'])
x.columns

X shape: (1818, 41)
Y shape: (1818, 1)

Index(['tempo', 'chroma_stft_mean', 'chroma_stft_var', 'rms_mean', 'rms_var',
       'spectral_centroid_mean', 'spectral_centroid_var',
       'spectral_bandwidth_mean', 'spectral_bandwidth_var',
       'spectral_rolloff_mean', 'spectral_rolloff_var',
       'zero_crossing_rate_mean', 'zero_crossing_rate_var', 'tonnetz_mean',
       'tonnetz_var', 'mfcc_1_mean', 'mfcc_1_var', 'mfcc_2_mean', 'mfcc_2_var',
       'mfcc_3_mean', 'mfcc_3_var', 'mfcc_4_mean', 'mfcc_4_var', 'mfcc_5_mean',
       'mfcc_5_var', 'mfcc_6_mean', 'mfcc_6_var', 'mfcc_7_mean', 'mfcc_7_var',
       'mfcc_8_mean', 'mfcc_8_var', 'mfcc_9_mean', 'mfcc_9_var',
       'mfcc_10_mean', 'mfcc_10_var', 'mfcc_11_mean', 'mfcc_11_var',
       'mfcc_12_mean', 'mfcc_12_var', 'mfcc_13_mean', 'mfcc_13_var'],
      dtype='object')

### Data Scaling

In [ ]:
#function to scale dataset
def stand_scale(data):
    scaled = ((x - x.mean(axis=0)) / x.std(axis=0))

    return scaled

In [ ]:
#mean and std before standard scaling
x.describe().T[["mean", "std"]]

                                 mean           std
tempo                    1.226104e+02  2.233850e+01
chroma_stft_mean         3.558407e-01  7.029410e-02
chroma_stft_var          8.783250e-02  7.129222e-03
rms_mean                 1.470892e-01  8.525706e-02
rms_var                  3.976259e-03  4.605240e-03
spectral_centroid_mean   1.946576e+03  5.522269e+02
spectral_centroid_var    4.888274e+05  3.877958e+05
spectral_bandwidth_mean  2.157611e+03  4.321839e+02
spectral_bandwidth_var   2.058261e+05  1.579403e+05
spectral_rolloff_mean    4.038379e+03  1.250180e+03
spectral_rolloff_var     2.269368e+06  1.491137e+06
zero_crossing_rate_mean  8.720387e-02  3.272813e-02
zero_crossing_rate_var   2.564892e-03  3.261712e-03
tonnetz_mean             1.065851e-02  3.144557e-02
tonnetz_var              1.991885e-02  1.462050e-02
mfcc_1_mean             -1.530360e+02  1.077031e+02
mfcc_1_var               4.755819e+03  5.110996e+03
mfcc_2_mean              1.059531e+02  2.955600e+01
mfcc_2_var               9.583377e+02  6.629677e+02
mfcc_3_mean             -3.462445e-01  2.071979e+01
mfcc_3_var               4.702747e+02  3.148228e+02
mfcc_4_mean              2.571377e+01  1.107800e+01
mfcc_4_var               2.367471e+02  1.385926e+02
mfcc_5_mean              4.397514e+00  8.033047e+00
mfcc_5_var               1.822407e+02  1.094804e+02
mfcc_6_mean              6.611014e+00  8.140108e+00
mfcc_6_var               1.513701e+02  9.705196e+01
mfcc_7_mean             -9.740949e-01  6.918943e+00
mfcc_7_var               1.235289e+02  6.090230e+01
mfcc_8_mean              3.066726e+00  6.127802e+00
mfcc_8_var               1.076759e+02  6.236457e+01
mfcc_9_mean             -3.222894e+00  6.430196e+00
mfcc_9_var               1.041153e+02  5.224290e+01
mfcc_10_mean             4.329954e+00  5.471615e+00
mfcc_10_var              9.681810e+01  4.848533e+01
mfcc_11_mean            -4.141159e+00  5.131592e+00
mfcc_11_var              9.397434e+01  5.068939e+01
mfcc_12_mean             2.586286e+00  4.310203e+00
mfcc_12_var              8.449635e+01  4.539232e+01
mfcc_13_mean            -2.882896e+00  4.735333e+00
mfcc_13_var              8.442676e+01  4.630661e+01

In [ ]:
# B) Data Scaling:
# Scale the features using a standard scaling approach.
# Print the means and standard deviations for each column in the scaled dataset.
# FYI: all the means should be very small numbers close to zero, while all the standard deviations should be equal to one

x_scaled = stand_scale(x)
x_scaled.describe().T[["mean", "std"]]

                                 mean  std
tempo                   -8.363924e-16  1.0
chroma_stft_mean        -1.563350e-17  1.0
chroma_stft_var         -2.626429e-15  1.0
rms_mean                -1.876020e-16  1.0
rms_var                  7.816752e-17  1.0
spectral_centroid_mean  -1.719685e-16  1.0
spectral_centroid_var    7.816752e-17  1.0
spectral_bandwidth_mean  7.738584e-16  1.0
spectral_bandwidth_var  -1.563350e-17  1.0
spectral_rolloff_mean   -1.719685e-16  1.0
spectral_rolloff_var    -2.032355e-16  1.0
zero_crossing_rate_mean -4.690051e-17  1.0
zero_crossing_rate_var  -2.345026e-17  1.0
tonnetz_mean            -2.540444e-17  1.0
tonnetz_var              0.000000e+00  1.0
mfcc_1_mean             -7.230495e-17  1.0
mfcc_1_var              -7.816752e-18  1.0
mfcc_2_mean              3.126701e-16  1.0
mfcc_2_var               1.563350e-17  1.0
mfcc_3_mean              1.954188e-17  1.0
mfcc_3_var              -7.816752e-17  1.0
mfcc_4_mean             -2.188690e-16  1.0
mfcc_4_var               6.253401e-17  1.0
mfcc_5_mean              3.908376e-17  1.0
mfcc_5_var               1.250680e-16  1.0
mfcc_6_mean             -6.253401e-17  1.0
mfcc_6_var               1.250680e-16  1.0
mfcc_7_mean              3.126701e-17  1.0
mfcc_7_var              -9.380102e-17  1.0
mfcc_8_mean              1.094345e-16  1.0
mfcc_8_var               0.000000e+00  1.0
mfcc_9_mean              1.563350e-17  1.0
mfcc_9_var               2.188690e-16  1.0
mfcc_10_mean            -1.563350e-17  1.0
mfcc_10_var              0.000000e+00  1.0
mfcc_11_mean            -3.126701e-17  1.0
mfcc_11_var              9.380102e-17  1.0
mfcc_12_mean            -9.380102e-17  1.0
mfcc_12_var             -1.407015e-16  1.0
mfcc_13_mean            -3.126701e-17  1.0
mfcc_13_var              0.000000e+00  1.0

### Train Test Split

In [ ]:
# C) Train/Test Split:
# Perform a train/test split on the target and scaled features. Use 20% of the rows in the test set. Use a random state for reproducibility.
# Print the shape of each of the resulting four datasets.

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y,
                                                    test_size=0.2,
                                                    random_state=21)
print("TRAIN:", x_train.shape, y_train.shape)
print("TEST:", x_test.shape, y_test.shape)

TRAIN: (1454, 41) (1454, 1)
TEST: (364, 41) (364, 1)

### Model Training

In [ ]:
# D) Model Training:
# Using a LogisticRegression model from sklearn, train the model on the training data.
model = LogisticRegression(random_state=21)
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

LogisticRegression(random_state=21)

In [ ]:
# Inspect the coefficients. Print the shape of the coefficients.
print(f"Shape of Coefficients: {model.coef_.shape}\nCoefficients: \n{model.coef_}")

Shape of Coefficients: (24, 41)
Coefficients:
[[ 2.35367890e-01  7.99529363e-01 -7.36492179e-01  1.31820758e-01
  -5.26786408e-01  5.39934932e-01  7.67471341e-02  2.48280391e-01
   6.55748899e-01  5.10219017e-01  4.07903761e-01  8.18885446e-01
  -2.31719936e-01  7.03678240e-02 -7.78804522e-01  1.21467678e+00
   1.00655934e-01 -3.31231916e-01 -5.90472799e-02 -1.32816447e+00
   7.79857090e-01 -2.19682754e-01  6.29605986e-01  1.58447064e+00
  -7.02385794e-01  1.33617378e-01  4.29969670e-01 -7.43264403e-01
  -3.43389809e-01  4.51024126e-02  1.83916708e-01 -2.10226378e-01
  -3.80371141e-01 -1.70946234e-01 -6.69635716e-01  1.21726478e+00
  -9.54303037e-02  2.31286749e-01 -2.77532393e-01 -6.29509792e-01
  -2.55789505e-01]
 [ 2.69169921e-01  7.35768971e-02  1.46707119e-01  1.07707913e+00
   4.46275163e-01  3.35334373e-01  9.82280708e-02 -4.45904979e-01
   3.20666732e-01 -1.49387664e-02  4.45233148e-01  1.05818631e+00
  -2.05286255e-01  3.61530862e-02  2.78597909e-01 -2.12580315e+00
  -2.86812194e-01  4.78343080e-01  5.78522761e-02 -4.04941601e-01
  -4.70727710e-01 -1.38192239e+00  5.32221935e-01  2.96158033e-01
  -1.40562824e+00  2.10121687e-01  3.33288037e-01 -2.84520202e-02
  -7.78106804e-01  1.14334753e+00  2.77517809e-01 -7.89828431e-02
   4.02425688e-01  1.03981580e+00  6.29987368e-01 -7.75825451e-01
   1.06948349e-01  6.73656540e-01 -4.86883870e-01 -1.07731214e+00
   2.31141846e-01]
 [-4.18251342e-01  5.55522695e-01  5.12289311e-01  1.19523130e+00
  -2.64261933e-01 -6.76134077e-01  3.73759855e-01 -7.87279208e-01
  -1.15726946e+00 -9.69960803e-02  1.07689780e-01 -1.14494799e+00
  -5.79739756e-01  4.01736113e-01 -1.15946059e+00 -9.67661665e-01
   1.35814135e-01 -1.89108737e-01 -1.68913562e-01 -4.82419629e-01
  -6.46457282e-01 -5.02830511e-01  9.65859334e-01 -3.11714212e-01
  -6.52831916e-01 -1.26754776e+00 -2.56198236e-02  7.22930955e-01
   6.40128489e-01 -2.81695400e-01  6.55570611e-01 -3.42369777e-02
  -1.31162388e-01  1.01357633e+00  1.50067411e+00 -2.62559971e-01
   4.51823637e-01 -4.27102357e-01  9.93093618e-02  1.00464106e+00
  -5.59280021e-01]
 [-4.48590163e-01 -8.10871695e-01 -2.06415903e-01  2.97006889e-01
   3.59575418e-01 -5.37025183e-01  4.43388885e-01  1.10823931e-01
  -6.52057366e-01 -1.07002401e+00 -1.24225325e-01  5.74596548e-02
  -1.04038990e-01 -2.38940613e-01  2.91760223e-02  1.53799270e-01
  -3.79852918e-01 -1.62352175e-02  4.05111404e-01  1.15459549e+00
   7.98633621e-01  6.72787137e-02 -1.43868925e-01  9.03364219e-01
   3.16470881e-01 -9.56841748e-01  6.99115288e-03  1.79877120e+00
   1.33060443e-01 -1.34288742e-01 -7.26752314e-02 -1.98088777e+00
   2.53368514e-01  5.45062342e-01 -7.04313120e-01 -8.24542065e-01
   4.70986576e-01 -3.55955472e-01 -2.82221056e-01  1.74111116e-02
   8.47893787e-01]
 [ 2.04160157e-01  1.16380678e+00  5.36918193e-01  1.84231526e+00
   1.25059591e-01  7.90788093e-02 -5.88498822e-02  2.54976477e-01
   2.56813904e-01  1.02041273e+00  5.50666346e-01 -1.09734177e+00
  -5.41825669e-01 -1.24869168e+00 -1.20722471e-01 -3.86222516e-01
   9.06324626e-02 -5.04296761e-01  9.71709309e-01 -1.68280890e-01
  -4.22182758e-02 -5.93577622e-01  9.02249191e-01  4.40668784e-02
  -9.30860010e-01 -3.90267009e-01  5.72132795e-01  5.42997650e-01
  -2.70987795e-01 -1.14732371e+00  3.58195554e-01  8.88617454e-01
   3.73175090e-01  1.65853858e-01  4.65743731e-01 -1.36046184e+00
   1.00326472e+00  5.80159844e-01  3.97027542e-01  1.19900015e-01
  -1.03591137e+00]
 [-6.42073745e-01 -2.53832034e-01 -1.07680912e+00 -1.07983646e+00
  -2.87041167e-01 -6.68999324e-01 -3.84825923e-01 -1.16487823e+00
   1.79650453e-02 -3.18327014e-01 -5.35798912e-01  1.01033243e+00
  -3.43876062e-03 -6.33190796e-01  8.88380417e-01 -4.04143414e-01
   9.70381534e-02  5.27442832e-01  4.73997359e-01 -5.94836306e-01
  -5.69999073e-01  2.77258529e-01 -1.13482343e+00 -7.14413191e-01
  -2.21084258e-02 -1.81645337e+00 -6.07236874e-01  2.83150027e-01
   4.37134061e-01  7.56307047e-01 -8.69209729e-01 -2.20191508e-01
   2.59976592e-01  3.19479008e-01  3.90990627e-01 -6.03288787e-01
   6.09683015e-01  7.54300921e-01  8.79691988e-01  6.93283750e-01
   2.46709461e-01]
 [ 1.36635174e-01 -1.99584688e+00 -1.43287564e+00 -5.34784703e-01
  -8.81219698e-02 -3.77315863e-01 -3.24521446e-01 -9.90179455e-01
  -1.55995357e+00 -6.04165429e-01 -8.96020525e-01  5.02293478e-01
   1.50803262e-01  4.92400355e-03 -8.88783560e-01 -2.09020810e+00
   2.91391801e-01  2.54635340e-01 -1.67943365e-02  1.01533677e+00
   1.01377435e-01 -3.87391805e-01  6.69915420e-02 -1.43736385e-01
  -2.18045253e-01 -2.21415702e-01 -1.05267367e-01 -2.61816512e-01
  -1.70578794e-01  3.38252178e-01 -8.47892480e-01 -2.40043208e-01
  -4.52453705e-01 -2.94631202e-01 -5.25535809e-01 -2.51164006e-01
   2.22320553e-01  6.26915027e-01  5.35256296e-01  5.07887390e-01
   3.06239908e-01]
 [-3.36277565e-01  1.06164409e-01 -5.52779346e-01 -1.88078005e-02
   7.74554277e-01 -9.26116797e-02  3.37143998e-01 -1.04585056e+00
  -3.47402741e-01 -1.02183513e+00  8.96367610e-01  1.69281580e+00
  -3.44240756e-01  5.19656213e-01  1.00169795e-01 -2.89544516e-01
  -4.14342160e-02  1.75534591e-01 -1.32166775e+00  6.39808208e-01
  -1.27555737e+00 -6.47489782e-02 -1.89005226e-01 -1.07179007e+00
   7.38783953e-01  1.57823073e+00 -8.26481428e-01 -1.89500878e+00
   1.99971342e-01  8.52404799e-01  4.38263285e-01 -9.48853325e-01
   4.97238933e-01 -4.02577210e-01 -1.39215567e+00  1.27057039e+00
  -8.35655018e-01 -3.37274680e-01 -1.36048595e+00  5.47949388e-02
  -6.24503919e-01]
 [ 4.48140419e-02  1.55868537e-01  6.50817111e-01  9.45118620e-02
   7.07645402e-02 -6.08773562e-01  1.42077590e-01 -1.34646252e+00
  -1.97814754e-01  1.27454667e-01 -3.76734525e-01  3.73267742e-01
   4.46936883e-01 -4.67348641e-01  1.28377891e+00  7.42500291e-01
  -6.42333721e-02 -7.28059007e-01  1.27761529e-01 -1.55481034e-01
   5.28413974e-01  5.93097343e-01 -1.12898588e+00 -1.99533138e-01
   4.01359687e-01  1.66687287e+00 -2.03526929e-01  4.59654828e-01
   2.82421157e-01 -7.55622747e-01  6.36726308e-01  1.78825977e+00
  -3.94100360e-01 -8.96134401e-01  2.25906093e-01 -5.81607816e-01
  -5.16772002e-01  3.28864870e-02  3.85535528e-01  5.27120215e-01
  -6.97041172e-01]
 [-1.05187398e-01 -6.98110667e-01 -7.70057454e-01  3.30433621e-01
  -7.32810527e-01  2.55917416e-01  5.46842403e-01 -3.94102231e-01
   3.40415959e-01 -3.97718448e-01 -9.89285412e-01 -3.07187811e-01
   8.00768330e-01 -4.11128552e-01  5.01668265e-01  5.42382054e-02
   4.42976220e-01 -6.65481284e-01 -3.48905804e-01 -8.30096947e-01
  -6.06137388e-01  1.81748234e-01 -5.87773252e-01 -4.04477987e-01
   2.42929355e-01  1.21649537e+00 -1.12510348e-01 -9.16144835e-01
  -3.78234493e-01  5.81620829e-01  5.05420976e-01  1.31766504e-01
  -5.99908188e-02 -1.48130205e+00  5.82954926e-01  1.11437643e+00
   1.60031242e-02 -8.93516076e-01 -1.16536386e+00  7.42041543e-01
   4.41111417e-01]
 [-1.36364062e-01  2.82299888e-01 -7.14957479e-01 -3.59110222e-01
   1.27155395e+00  9.37250975e-01  1.10573370e+00  7.96402348e-01
   8.32714543e-01  1.11852716e+00 -1.13941054e-01  4.23753669e-01
  -1.16131651e+00  3.73328494e-01 -5.91048477e-01 -6.98565604e-02
   2.20255488e-01 -5.37943331e-01  9.65719668e-01 -2.63289741e-02
  -7.50543038e-01  9.25731090e-01  6.13843379e-01 -9.52590521e-01
   1.49404052e+00  3.55856955e-02  2.79363107e-01  2.57807355e-01
  -6.10087723e-02  8.52853372e-01 -8.94736235e-01 -6.32467735e-01
   1.32620465e+00  1.00828039e+00  4.77941078e-01 -3.00394864e-01
   6.30743487e-02 -1.96888582e-01  3.41265650e-01  6.40772621e-02
  -3.33023380e-01]
 [-9.42014148e-02 -9.30191792e-01  4.49314619e-01 -9.13714558e-01
  -5.56491085e-01 -5.09157706e-02  2.27202747e-01 -3.79102804e-02
  -3.47738671e-01  1.98631790e-01  3.90533727e-01  4.96258773e-01
   3.50300771e-01 -8.08009289e-02 -3.26218799e-01  1.42069138e+00
   9.26810733e-01  7.06764547e-01 -3.32819764e-01  4.73907398e-01
   3.19665162e-01  1.97362166e+00 -9.73583440e-01 -1.52532504e+00
   1.09732091e+00  9.88931319e-01 -6.36607762e-01 -8.81742239e-01
   3.09574543e-01 -5.03297460e-01 -2.45370272e-01 -4.15511939e-01
  -1.26394013e+00 -9.00600734e-01 -4.64616821e-02  4.66766576e-01
  -3.17310668e-01  3.07109393e-01  3.70067584e-01  6.41553317e-02
  -7.99071818e-01]
 [ 2.99334472e-01 -2.93949975e-01 -3.85897515e-01 -8.33332173e-01
  -1.09208102e+00 -1.37566693e-01  3.62736145e-01  2.96550861e-01
   5.45242943e-01  4.51759245e-01 -3.51893055e-01 -5.52674711e-01
  -1.25754909e-01 -4.89946944e-01 -6.27400564e-02  1.52524499e+00
   3.39892495e-01 -3.73285604e-01  2.77613934e-01  4.47725947e-02
   4.31511012e-01  4.71597685e-01 -1.30541110e-01  9.14516877e-01
  -2.59928447e-01 -1.11962247e+00 -1.59737387e-01  2.11717842e-01
  -5.51769381e-01  6.91346976e-01  6.32079486e-01 -7.08364310e-01
   7.02221827e-01 -3.67376604e-01  1.12639069e-01  5.08909048e-01
  -8.34554272e-01 -9.79888517e-01  2.75103166e-01  2.40722106e-01
  -2.52088207e-01]
 [ 5.96135811e-01  1.56943263e+00  3.81054325e-01  1.00078233e-01
   6.12942309e-01  5.72320313e-01  5.82770186e-01 -5.36679880e-01
  -1.29881128e-01 -1.45781648e-01  1.99170671e-01 -6.68864172e-02
   3.33893335e-01  2.68810377e-01 -2.18621741e-01  2.83835691e-01
  -2.71256129e-01  1.00169959e-01 -2.62665431e-03 -1.85054766e+00
  -9.21071803e-01 -3.06194962e-01 -5.16023789e-01  5.89192701e-02
  -5.17434215e-02 -3.72432033e-01  1.71505852e+00  3.57801606e-01
  -1.17900863e-01  9.12998271e-01  6.83860392e-01 -1.52096234e+00
   8.91464365e-01  9.29048846e-01  2.25248756e-03  1.21770245e-01
  -7.12322597e-01 -5.64329324e-01 -5.63701081e-01  6.77277624e-01
  -5.76585361e-03]
 [ 4.29280766e-01 -1.64976428e+00  1.20300282e+00 -8.40198912e-01
  -3.87447990e-01 -5.17039272e-01 -5.23926263e-01  8.60123853e-01
  -1.05809354e+00  1.27359197e-01  2.20369956e-01 -9.42158414e-01
   3.74042394e-01 -4.50716788e-01 -1.36819078e-01 -1.15537588e-01
  -7.81609598e-01  7.44221404e-02 -4.44921207e-01  1.98380112e+00
   1.49441848e+00 -4.85574773e-01 -6.73666989e-01  6.17543343e-01
  -3.79303401e-02  1.80273799e-01 -1.09912568e+00 -1.43267297e+00
  -2.47647924e-01 -1.54521791e+00 -1.38992888e-01  3.08549375e-01
  -1.16874678e+00  6.83356978e-01 -5.31066762e-01 -7.42885266e-01
  -5.76513278e-01  6.77101865e-01  1.84964949e-01  6.17604829e-02
   7.80399263e-01]
 [-2.52408336e-01 -3.96537342e-01 -1.11666308e-01 -1.26990359e-01
   1.24156198e+00  2.87924148e-01  4.15750887e-01 -1.32883228e-01
   5.08848241e-01  8.73995102e-01  1.22617875e-01 -3.72090168e-01
  -5.75821658e-01 -1.52827653e-03  5.28113371e-02 -3.82329755e-01
  -6.64095852e-01 -6.36781136e-02  3.62216813e-01  2.48420558e-01
  -1.54602610e+00 -6.14974506e-01  4.15111569e-01  5.96538182e-01
   1.18025799e+00 -6.70122198e-01 -3.05278178e-01 -6.02098996e-01
  -2.42789934e-01  1.81792145e-01  3.52359011e-02  3.58165445e-02
  -1.41552496e+00  1.62676840e-02  4.66221961e-01  6.53465157e-01
   1.32430405e+00 -3.91317667e-01  2.67353677e-01 -2.45092721e-01
   7.48131554e-02]
 [-1.40933738e-01  1.65104855e-01  2.55243790e-01  1.28100560e+00
   4.30726967e-02 -9.83025459e-01  1.35909864e-01  3.69495288e-01
  -1.82133915e-01 -1.02283339e+00  5.73111958e-01 -1.30767010e+00
   1.63942929e-01 -1.59917099e-01  1.02728392e+00  8.96742572e-01
  -1.09195314e-02 -3.07426692e-01  2.28216955e-01 -1.83440033e-01
   5.01018614e-01  7.18909160e-01 -3.01217574e-01 -4.63450121e-01
  -7.09730009e-02  2.73074811e-01  4.38443292e-01 -9.69760726e-01
  -5.68595359e-02 -8.85662462e-01 -1.24708156e-01  1.29394941e+00
   6.09372858e-01 -3.57289968e-01 -9.00988233e-01  6.65899270e-01
  -2.80906919e-01 -3.94670064e-01 -7.56806273e-01  2.49161527e-01
  -1.27253921e+00]
 [-1.98439944e-01  4.89046645e-01  3.29321951e-01 -1.04080703e+00
  -1.24310856e+00  3.18495455e-01 -1.48674376e+00  8.35080044e-01
  -6.77269335e-01 -6.14194953e-03  6.62387591e-01  6.31298294e-01
  -3.30156352e-01  1.29645396e+00  7.63033737e-02  7.82508598e-01
   6.74820945e-01  3.72855494e-01  7.02943243e-01 -9.06063373e-01
   5.13768863e-02  1.02836534e+00 -5.89577090e-01 -2.13240883e-01
   6.32167237e-01  1.10905332e+00 -2.52386363e-01  8.02133322e-01
  -3.04124575e-01 -6.35031629e-01 -5.03242437e-01  1.09833664e+00
   8.41170750e-01 -2.13932130e+00 -2.56234642e-01  5.71585525e-01
  -8.18013296e-01 -4.47923778e-01 -3.48525351e-01 -8.07514422e-01
   6.17686322e-01]
 [-2.91057903e-01  1.27488798e+00  2.18501121e-01  9.63826751e-01
   3.97829453e-01 -2.65457009e-01 -6.32610728e-01  3.61801785e-01
  -2.69381838e-01  1.79355332e-01 -3.55767391e-01 -8.22557384e-01
  -5.88413722e-01  2.28951836e-01 -4.80576437e-01  2.66480196e-01
   6.70983257e-01  3.95283510e-01  1.79429621e-01  4.91500150e-01
   3.29955853e-01 -7.72820040e-01  3.73710127e-01  2.39371952e-01
  -2.20021858e-01 -1.85801214e-01  5.37482195e-01  7.24302637e-01
   3.03884825e-01 -6.30351124e-01 -2.98484345e-01  3.18576799e-01
  -8.88527832e-01 -1.22959760e-01 -7.05229108e-01 -1.94769810e+00
  -2.52797045e-02  1.30501225e+00  8.78111202e-01 -1.12091551e+00
   1.99837575e+00]
 [ 4.76769509e-02 -2.45391254e+00  9.11657174e-01 -9.14788214e-01
   7.12933628e-01  8.43635594e-01 -1.03204835e+00  7.30110519e-02
  -8.01048998e-02 -4.39232898e-02  4.01117492e-01 -1.65077989e-01
   8.61897220e-01  2.43090424e-01 -2.34410735e-01 -1.95929836e+00
  -1.13560456e+00  1.15672700e-01  9.08209215e-02 -3.54707030e-01
   1.07958273e+00  2.48006097e-01  7.74373319e-01 -1.57478645e-01
  -1.43562676e+00  2.15014039e-01 -1.32959217e+00 -5.43542387e-01
   2.84125957e-01 -2.78761569e-02 -8.44537399e-01 -1.75807447e+00
   3.69122838e-01  1.08917304e+00 -3.22965319e-02  4.26160503e-01
  -5.09578615e-01  5.48208792e-01  4.41537378e-01  8.27408359e-01
  -1.11305928e-04]
 [ 2.15785271e-01 -2.20160033e-02 -6.81776937e-01 -4.22336599e-01
  -5.29927300e-01 -5.09178313e-01 -1.03855396e+00  1.45450698e+00
   6.07950024e-01 -5.93532167e-01  2.57961718e-01  1.25211901e+00
   5.07131809e-01  8.92353812e-02  7.15582594e-01 -1.11088123e+00
  -6.26057729e-01  1.53872689e+00 -8.13505554e-01  2.12593966e-01
  -5.06673735e-03 -1.29752568e-01  3.56986815e-01  1.60727321e+00
   3.68294432e-01  1.58585703e-01 -6.06014252e-01 -2.99387260e-01
  -1.59867801e-01  1.14574272e-01 -8.53182520e-01  4.46829368e-01
  -3.72357246e-01 -1.79545131e-01  3.59375279e-01  5.08098256e-01
   5.34980526e-01 -5.33178984e-01  1.15231278e-01 -8.32562460e-01
   5.30904608e-01]
 [ 3.84064949e-01  4.23824580e-01  9.44936764e-01  1.74145673e-02
  -4.32444646e-01  4.12187665e-01 -3.13938831e-01  2.34322753e-01
   1.09326863e+00  1.97015527e-01 -3.81596909e-01 -3.08763145e-01
   1.49291204e-01 -5.51224684e-01  8.41512513e-01  8.94409801e-01
  -1.67736273e-01 -1.30526531e+00  8.25469096e-02  6.08981640e-01
   9.89553146e-02 -1.05763044e+00 -5.22701450e-01 -2.13557250e-01
  -5.44164261e-01 -9.06303747e-01  1.11415921e+00  9.92487708e-01
   6.47915549e-01  3.73004656e-02  5.03661447e-01  1.75753696e+00
  -2.00537298e-02 -1.17975580e-01  5.97610708e-01  1.08415223e+00
   8.76681366e-03 -2.10854641e-03  8.00006186e-02 -7.72455504e-01
   2.64020927e-04]
 [-2.51408804e-01  5.24312388e-01 -3.08858777e-01 -7.56722726e-03
   2.46530628e-01  4.76654898e-01  4.97674706e-01  4.57520380e-01
   8.48644531e-01 -2.53157671e-01 -1.21141645e-01 -6.39935382e-01
   4.23652873e-01  1.47555825e+00 -5.15021072e-01 -6.04828975e-02
   3.12572966e-01  3.61265588e-01 -8.11757373e-01 -2.68745816e-02
   1.55352691e-01 -2.37409990e-01  5.33270374e-01 -7.79364459e-01
  -4.88902005e-01 -1.15953756e+00  9.70359804e-01  1.26422080e+00
   5.84416766e-01 -5.11259882e-02  2.10526322e-01  9.80339682e-01
  -1.01682516e-01  2.15611898e-01 -1.83488003e-01 -4.91457302e-01
   6.71085335e-01  3.46840769e-01 -6.62651032e-01 -3.76253501e-01
  -4.36982954e-01]
 [ 4.52769012e-01  1.92165556e+00  4.38822358e-01 -2.38449709e-01
  -1.62131023e-01  3.65307630e-01  4.50052966e-01  5.29234426e-01
   6.30821767e-01  7.84645214e-01 -9.88726879e-01 -5.89379317e-01
   2.29092259e-01 -2.74830957e-01 -2.82037518e-01  1.72684199e+00
   1.25767777e-01 -7.91047014e-02 -6.04980656e-01  4.38464641e-01
   1.63685918e-01  2.68897479e-01  7.27544585e-01  2.88449302e-01
   5.69524786e-01  1.30048808e+00 -1.27863223e-01  1.55915198e-01
  -1.39366650e-01  8.95930410e-02  5.72056891e-01 -2.99775711e-01
   1.23169498e-01  4.05134005e-01  1.35107840e-01 -4.67132935e-01
   3.90956326e-02 -5.59324594e-01  6.53714648e-01  9.97332693e-03
   1.96569177e-01]]

In a text cell, write what the shape represents.

Interpretation of the coefficients:

- The coefficients have 24 rows and 41 columns. For each artist classification, the model has generated a value fo each feature which shows the relationship between each feature and the class.

In [ ]:
# Display the coefficients as a pandas.DataFrame, with appropriate index values and column names.
coefs = pd.DataFrame(model.coef_.T, columns = model.classes_, index=x_train.columns)
coefs

,ac_dc,adele,alicia_keys,andrea_bocelli,ariana_grande,bach,beethoven,bruce_springsteen,chris_stapleton,coldplay,...,john_coltrane,john_legend,john_mayer,led_zeppelin,maggie_rogers,miles_davis,pink_floyd,rihanna,taylor_swift,tupac
tempo,0.235368,0.269170,-0.418251,-0.448590,0.204160,-0.642074,0.136635,-0.336278,0.044814,-0.105187,...,0.429281,-0.252408,-0.140934,-0.198440,-0.291058,0.047677,0.215785,0.384065,-0.251409,0.452769
chroma_stft_mean,0.799529,0.073577,0.555523,-0.810872,1.163807,-0.253832,-1.995847,0.106164,0.155869,-0.698111,...,-1.649764,-0.396537,0.165105,0.489047,1.274888,-2.453913,-0.022016,0.423825,0.524312,1.921656
chroma_stft_var,-0.736492,0.146707,0.512289,-0.206416,0.536918,-1.076809,-1.432876,-0.552779,0.650817,-0.770057,...,1.203003,-0.111666,0.255244,0.329322,0.218501,0.911657,-0.681777,0.944937,-0.308859,0.438822
rms_mean,0.131821,1.077079,1.195231,0.297007,1.842315,-1.079836,-0.534785,-0.018808,0.094512,0.330434,...,-0.840199,-0.126990,1.281006,-1.040807,0.963827,-0.914788,-0.422337,0.017415,-0.007567,-0.238450
rms_var,-0.526786,0.446275,-0.264262,0.359575,0.125060,-0.287041,-0.088122,0.774554,0.070765,-0.732811,...,-0.387448,1.241562,0.043073,-1.243109,0.397829,0.712934,-0.529927,-0.432445,0.246531,-0.162131
spectral_centroid_mean,0.539935,0.335334,-0.676134,-0.537025,0.079079,-0.668999,-0.377316,-0.092612,-0.608774,0.255917,...,-0.517039,0.287924,-0.983025,0.318495,-0.265457,0.843636,-0.509178,0.412188,0.476655,0.365308
spectral_centroid_var,0.076747,0.098228,0.373760,0.443389,-0.058850,-0.384826,-0.324521,0.337144,0.142078,0.546842,...,-0.523926,0.415751,0.135910,-1.486744,-0.632611,-1.032048,-1.038554,-0.313939,0.497675,0.450053
spectral_bandwidth_mean,0.248280,-0.445905,-0.787279,0.110824,0.254976,-1.164878,-0.990179,-1.045851,-1.346463,-0.394102,...,0.860124,-0.132883,0.369495,0.835080,0.361802,0.073011,1.454507,0.234323,0.457520,0.529234
spectral_bandwidth_var,0.655749,0.320667,-1.157269,-0.652057,0.256814,0.017965,-1.559954,-0.347403,-0.197815,0.340416,...,-1.058094,0.508848,-0.182134,-0.677269,-0.269382,-0.080105,0.607950,1.093269,0.848645,0.630822
spectral_rolloff_mean,0.510219,-0.014939,-0.096996,-1.070024,1.020413,-0.318327,-0.604165,-1.021835,0.127455,-0.397718,...,0.127359,0.873995,-1.022833,-0.006142,0.179355,-0.043923,-0.593532,0.197016,-0.253158,0.784645
spectral_rolloff_var,0.407904,0.445233,0.107690,-0.124225,0.550666,-0.535799,-0.896021,0.896368,-0.376735,-0.989285,...,0.220370,0.122618,0.573112,0.662388,-0.355767,0.401117,0.257962,-0.381597,-0.121142,-0.988727
zero_crossing_rate_mean,0.818885,1.058186,-1.144948,0.057460,-1.097342,1.010332,0.502293,1.692816,0.373268,-0.307188,...,-0.942158,-0.372090,-1.307670,0.631298,-0.822557,-0.165078,1.252119,-0.308763,-0.639935,-0.589379
zero_crossing_rate_var,-0.231720,-0.205286,-0.579740,-0.104039,-0.541826,-0.003439,0.150803,-0.344241,0.446937,0.800768,...,0.374042,-0.575822,0.163943,-0.330156,-0.588414,0.861897,0.507132,0.149291,0.423653,0.229092
tonnetz_mean,0.070368,0.036153,0.401736,-0.238941,-1.248692,-0.633191,0.004924,0.519656,-0.467349,-0.411129,...,-0.450717,-0.001528,-0.159917,1.296454,0.228952,0.243090,0.089235,-0.551225,1.475558,-0.274831
tonnetz_var,-0.778805,0.278598,-1.159461,0.029176,-0.120722,0.888380,-0.888784,0.100170,1.283779,0.501668,...,-0.136819,0.052811,1.027284,0.076303,-0.480576,-0.234411,0.715583,0.841513,-0.515021,-0.282038
mfcc_1_mean,1.214677,-2.125803,-0.967662,0.153799,-0.386223,-0.404143,-2.090208,-0.289545,0.742500,0.054238,...,-0.115538,-0.382330,0.896743,0.782509,0.266480,-1.959298,-1.110881,0.894410,-0.060483,1.726842
mfcc_1_var,0.100656,-0.286812,0.135814,-0.379853,0.090632,0.097038,0.291392,-0.041434,-0.064233,0.442976,...,-0.781610,-0.664096,-0.010920,0.674821,0.670983,-1.135605,-0.626058,-0.167736,0.312573,0.125768
mfcc_2_mean,-0.331232,0.478343,-0.189109,-0.016235,-0.504297,0.527443,0.254635,0.175535,-0.728059,-0.665481,...,0.074422,-0.063678,-0.307427,0.372855,0.395284,0.115673,1.538727,-1.305265,0.361266,-0.079105
mfcc_2_var,-0.059047,0.057852,-0.168914,0.405111,0.971709,0.473997,-0.016794,-1.321668,0.127762,-0.348906,...,-0.444921,0.362217,0.228217,0.702943,0.179430,0.090821,-0.813506,0.082547,-0.811757,-0.604981
mfcc_3_mean,-1.328164,-0.404942,-0.482420,1.154595,-0.168281,-0.594836,1.015337,0.639808,-0.155481,-0.830097,...,1.983801,0.248421,-0.183440,-0.906063,0.491500,-0.354707,0.212594,0.608982,-0.026875,0.438465
mfcc_3_var,0.779857,-0.470728,-0.646457,0.798634,-0.042218,-0.569999,0.101377,-1.275557,0.528414,-0.606137,...,1.494418,-1.546026,0.501019,0.051377,0.329956,1.079583,-0.005067,0.098955,0.155353,0.163686
mfcc_4_mean,-0.219683,-1.381922,-0.502831,0.067279,-0.593578,0.277259,-0.387392,-0.064749,0.593097,0.181748,...,-0.485575,-0.614975,0.718909,1.028365,-0.772820,0.248006,-0.129753,-1.057630,-0.237410,0.268897
mfcc_4_var,0.629606,0.532222,0.965859,-0.143869,0.902249,-1.134823,0.066992,-0.189005,-1.128986,-0.587773,...,-0.673667,0.415112,-0.301218,-0.589577,0.373710,0.774373,0.356987,-0.522701,0.533270,0.727545
mfcc_5_mean,1.584471,0.296158,-0.311714,0.903364,0.044067,-0.714413,-0.143736,-1.071790,-0.199533,-0.404478,...,0.617543,0.596538,-0.463450,-0.213241,0.239372,-0.157479,1.607273,-0.213557,-0.779364,0.288449
mfcc_5_var,-0.702386,-1.405628,-0.652832,0.316471,-0.930860,-0.022108,-0.218045,0.738784,0.401360,0.242929,...,-0.037930,1.180258,-0.070973,0.632167,-0.220022,-1.435627,0.368294,-0.544164,-0.488902,0.569525
mfcc_6_mean,0.133617,0.210122,-1.267548,-0.956842,-0.390267,-1.816453,-0.221416,1.578231,1.666873,1.216495,...,0.180274,-0.670122,0.273075,1.109053,-0.185801,0.215014,0.158586,-0.906304,-1.159538,1.300488
mfcc_6_var,0.429970,0.333288,-0.025620,0.006991,0.572133,-0.607237,-0.105267,-0.826481,-0.203527,-0.112510,...,-1.099126,-0.305278,0.438443,-0.252386,0.537482,-1.329592,-0.606014,1.114159,0.970360,-0.127863
mfcc_7_mean,-0.743264,-0.028452,0.722931,1.798771,0.542998,0.283150,-0.261817,-1.895009,0.459655,-0.916145,...,-1.432673,-0.602099,-0.969761,0.802133,0.724303,-0.543542,-0.299387,0.992488,1.264221,0.155915
mfcc_7_var,-0.343390,-0.778107,0.640128,0.133060,-0.270988,0.437134,-0.170579,0.199971,0.282421,-0.378234,...,-0.247648,-0.242790,-0.056860,-0.304125,0.303885,0.284126,-0.159868,0.647916,0.584417,-0.139367
mfcc_8_mean,0.045102,1.143348,-0.281695,-0.134289,-1.147324,0.756307,0.338252,0.852405,-0.755623,0.581621,...,-1.545218,0.181792,-0.885662,-0.635032,-0.630351,-0.027876,0.114574,0.037300,-0.051126,0.089593
mfcc_8_var,0.183917,0.277518,0.655571,-0.072675,0.358196,-0.869210,-0.847892,0.438263,0.636726,0.505421,...,-0.138993,0.035236,-0.124708,-0.503242,-0.298484,-0.844537,-0.853183,0.503661,0.210526,0.572057
mfcc_9_mean,-0.210226,-0.078983,-0.034237,-1.980888,0.888617,-0.220192,-0.240043,-0.948853,1.788260,0.131767,...,0.308549,0.035817,1.293949,1.098337,0.318577,-1.758074,0.446829,1.757537,0.980340,-0.299776
mfcc_9_var,-0.380371,0.402426,-0.131162,0.253369,0.373175,0.259977,-0.452454,0.497239,-0.394100,-0.059991,...,-1.168747,-1.415525,0.609373,0.841171,-0.888528,0.369123,-0.372357,-0.020054,-0.101683,0.123169
mfcc_10_mean,-0.170946,1.039816,1.013576,0.545062,0.165854,0.319479,-0.294631,-0.402577,-0.896134,-1.481302,...,0.683357,0.016268,-0.357290,-2.139321,-0.122960,1.089173,-0.179545,-0.117976,0.215612,0.405134
mfcc_10_var,-0.669636,0.629987,1.500674,-0.704313,0.465744,0.390991,-0.525536,-1.392156,0.225906,0.582955,...,-0.531067,0.466222,-0.900988,-0.256235,-0.705229,-0.032297,0.359375,0.597611,-0.183488,0.135108
mfcc_11_mean,1.217265,-0.775825,-0.262560,-0.824542,-1.360462,-0.603289,-0.251164,1.270570,-0.581608,1.114376,...,-0.742885,0.653465,0.665899,0.571586,-1.947698,0.426161,0.508098,1.084152,-0.491457,-0.467133
mfcc_11_var,-0.095430,0.106948,0.451824,0.470987,1.003265,0.609683,0.222321,-0.835655,-0.516772,0.016003,...,-0.576513,1.324304,-0.280907,-0.818013,-0.025280,-0.509579,0.534981,0.008767,0.671085,0.039096
mfcc_12_mean,0.231287,0.673657,-0.427102,-0.355955,0.580160,0.754301,0.626915,-0.337275,0.032886,-0.893516,...,0.677102,-0.391318,-0.394670,-0.447924,1.305012,0.548209,-0.533179,-0.002109,0.346841,-0.559325
mfcc_12_var,-0.277532,-0.486884,0.099309,-0.282221,0.397028,0.879692,0.535256,-1.360486,0.385536,-1.165364,...,0.184965,0.267354,-0.756806,-0.348525,0.878111,0.441537,0.115231,0.080001,-0.662651,0.653715
mfcc_13_mean,-0.629510,-1.077312,1.004641,0.017411,0.119900,0.693284,0.507887,0.054795,0.527120,0.742042,...,0.061760,-0.245093,0.249162,-0.807514,-1.120916,0.827408,-0.832562,-0.772456,-0.376254,0.009973
mfcc_13_var,-0.255790,0.231142,-0.559280,0.847894,-1.035911,0.246709,0.306240,-0.624504,-0.697041,0.441111,...,0.780399,0.074813,-1.272539,0.617686,1.998376,-0.000111,0.530905,0.000264,-0.436983,0.196569

In [ ]:
# Choose one of the artists, and using the coeficients, determine the top five most predictive features for that artist, and write them in a text cell.
coefs['taylor_swift'].sort_values(ascending = False)[:5]

tonnetz_mean              1.475558
mfcc_7_mean               1.264221
mfcc_9_mean               0.980340
mfcc_6_var                0.970360
spectral_bandwidth_var    0.848645
Name: taylor_swift, dtype: float64

The top five most predictive features for Taylor Swift are mfcc_7_mean (1.684767), tonnetz_mean (1.382950), mfcc_6_var (1.047179), mfcc_9_mean (0.844742), mfcc_2_mean (0.825044).

### Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix
import plotly.express as px

def plot_confusion_matrix(y_true, y_pred, height=450, showscale=False, title=None, subtitle=None):
    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
    # Confusion matrix whose i-th row and j-th column
    # ... indicates the number of samples with
    # ... true label being i-th class (ROW)
    # ... and predicted label being j-th class (COLUMN)
    cm = confusion_matrix(y_true, y_pred)

    class_names = sorted(y_test['artist_name'].unique().tolist())

    cm = confusion_matrix(y_test, y_pred, labels=class_names)

    title = title or "Confusion Matrix"
    if subtitle:
        title += f"<br><sup>{subtitle}</sup>"

    fig = px.imshow(cm, x=class_names, y=class_names, height=height,
                    labels={"x": "Predicted", "y": "Actual"},
                    color_continuous_scale="Blues", text_auto=True,
    )
    fig.update_layout(title={'text': title, 'x':0.485, 'xanchor': 'center'})
    fig.update_coloraxes(showscale=showscale)

    fig.show()

In [ ]:
# E) Model Evaluation:
# Evaluate the model using a classification report.

#predict test set
y_pred = model.predict(x_test)
#print classification report
print(classification_report(y_test, y_pred))

                   precision    recall  f1-score   support

            ac_dc       0.92      0.80      0.86        15
            adele       0.74      0.82      0.78        17
      alicia_keys       0.57      0.67      0.62         6
   andrea_bocelli       0.92      1.00      0.96        11
    ariana_grande       0.81      0.87      0.84        15
             bach       0.82      0.78      0.80        18
        beethoven       0.76      0.81      0.79        16
bruce_springsteen       0.75      0.75      0.75        24
  chris_stapleton       0.86      0.86      0.86        14
         coldplay       0.61      0.67      0.64        21
           dr_dre       0.85      0.85      0.85        13
    frank_sinatra       0.67      0.80      0.73         5
     jason_aldean       0.57      0.44      0.50         9
            jay_z       0.75      0.67      0.71        18
    john_coltrane       0.90      0.86      0.88        22
      john_legend       0.64      0.69      0.67        13
       john_mayer       0.72      0.93      0.81        14
     led_zeppelin       0.56      0.90      0.69        10
    maggie_rogers       0.89      0.53      0.67        15
      miles_davis       0.86      1.00      0.92        30
       pink_floyd       0.67      0.50      0.57        12
          rihanna       0.57      0.50      0.53         8
     taylor_swift       0.81      0.65      0.72        26
            tupac       1.00      0.83      0.91        12

         accuracy                           0.77       364
        macro avg       0.76      0.76      0.75       364
     weighted avg       0.78      0.77      0.77       364

In a text cell, interpret the classification report results, and describe how well the model did. What percent accuracy represents a "random chance guess" in this particular dataset? Which artists have the highest F1 scores, and which have the lowest?

Classification Report Interpretation:

- Accuracy - the model has an accuracy of 0.75. This indicates that the model did well as it predicted the correct artist for 75% of the songs in the test set correctly.
- Approximately 6.49% represents the random chance guess for this dataset since its an imbalanced dataset. This suggests that if the model were to make random guesses for the artist of each song without learning anything about the patterns and relationships in the data, it would correctly predict the artist for approximately 6.49% of the songs. There is a large difference between the accuracy of the model and the random chance guess. This indicates that the model has done a good job of capturing the patterns in the data and making predictions.
- Ac_Dc, Dr Dre and Bach have the highest f1 scores of 1, 0.92 and 0.92 respectively. This means that for ac_dc the model is doing a perfect job at correctly classifiying songs with their actual artists and it also does a perfect job at not misclassifying ac_dc songs as other artists'. The model also does a very good job at this for the classification of Dr Dre and Bach.
- John Legend, Led Zeppelin and Frank Sinatra have the lowest f1 scores of 0.44, 0.52 and 0.56 respectively. This means that the model doesn't do a great job and distinguishing between their songs and others well enough to correctly classify their songs. Additionally, the model doesn't do a great job at not misclassfying their songs with the songs of other artists.

In [ ]:
# Display a confusion matrix, ideally as a heatmap with color.
plot_confusion_matrix(y_test, y_pred, height=900)

In a text cell, write the names of the top three pairs of artists who were most confused with each other.

The three pairs of artists who were most confued with each other were:

1. Frank Cinatra and Cold Play - the model inaccurately predicted 4 Frank Cinatra songs as Cold Play songs.
2. John Mayer and Chris Stapleton - the model incorrectly predicted 3 John Mayer songs as Chris Stapleton songs.
3. Miles Davis and John Coltrane - the model incaccurately predicted 3 John Coltrane songs as Miles Davis songs.

## Part 4 - Dimensionality Reduction

Perform dimensionality reduction on the audio features.


A) Use a `PCA` model from `sklearn` with two components. Use a random state for reproducibility. **Train the model** on the scaled data (all rows) to obtain the embeddings.

B) Print the explained variance ratio for each component. Also print the **sum of explained variance** for all components. In a text cell, interpret these results.

C) Wrap the **embeddings** in a `pandas.DataFrame`, using appropriate column names ("component_1" and "component_2"), and appropriate index values.

D) **Plot the embeddings** using a scatterplot, with "component_1" on the x axis and "component_2" on the y axis. Color on artist label. In a text cell, interpret the plot.

E) **Calculate the centroids** for each artist. The centroid for a given artist is comprised of the "component_1" mean and the "component_2" mean for that artist.

F) **Plot the centroids** using a scatterplot, with "component_1" on the x axis and "component_2" on the y axis. Color on artist label. In a text cell, interpret the plot. Are there any artists who are in similar areas of the graph? Are there any artists who are more separable than others?

In [ ]:
# A) Use a PCA model from sklearn with two components. Use a random state for reproducibility. Train the model on the scaled data (all rows) to obtain the embeddings.
pca = PCA(n_components=2, random_state=21)

embeddings = pca.fit_transform(x_scaled)
print(f"Shape of the Embeddings: {embeddings.shape}")

Shape of the Embeddings: (1818, 2)

In [ ]:
# B) Print the explained variance ratio for each component. Also print the sum of explained variance for all components. In a text cell, interpret these results.
exp_var_ratio = pca.explained_variance_ratio_
exp_var_sum = sum(pca.explained_variance_)
sum_exp_ratio = 0

for i, j in enumerate(exp_var_ratio):
    sum_exp_ratio += j
    print(f"Principal Component {i+1}")
    print(f"    Explained Variance: {j}")
    print(f"    Cummulative Explained Variance: {sum_exp_ratio}")

print(f"\nSum of Explained Variance: {exp_var_sum}")

Principal Component 1
    Explained Variance: 0.21890505388738138
    Cummulative Explained Variance: 0.21890505388738138
Principal Component 2
    Explained Variance: 0.17100147326771664
    Cummulative Explained Variance: 0.389906527155098

Sum of Explained Variance: 15.986167613359019

Explained Variance Ratio and Explained Variance Interpretations:

- Principal component 1 has an explained variance ratio of approximately 0.2189. This means that approx. 21.89% of the total variance in the dataset is captured by the first principal component.
- Principal component 2 has an explained variance ratio of approximately 0.1710. This means that approx 17.10% of the total variance in the dataset is being captured by the second principal component.
- Together, PC1 and PC2 explains approx. 40% of the total variance in the dataset.
- The sum of explained variance from the results of the PCA is 15.99 which means that the first two components captures variance of 15.98 of the the dataset.

### Track Embeddings Plot

In [ ]:
# C) Wrap the embeddings in a pandas.DataFrame, using appropriate column names ("component_1" and "component_2"), and appropriate index values.
component_names = [f"component_{i+1}" for i in range(2)]

embeddings_df = pd.DataFrame(embeddings, columns = component_names, index = y['artist_name']).reset_index()
embeddings_df

        artist_name  component_1  component_2
0     frank_sinatra     2.202601     0.745840
1     frank_sinatra     2.491992     0.020364
2     frank_sinatra    -1.130122     0.444325
3     frank_sinatra     0.230034     0.480557
4     frank_sinatra    -1.256497    -0.141737
...             ...          ...          ...
1813   taylor_swift    -4.049552     4.266147
1814   taylor_swift    -0.139328     1.263042
1815   taylor_swift    -0.180542     2.521628
1816   taylor_swift    -4.761295     4.381796
1817   taylor_swift     3.567767     0.086380

[1818 rows x 3 columns]

In [ ]:
# D) Plot the embeddings using a scatterplot, with "component_1" on the x axis and "component_2" on the y axis. Color on artist label. In a text cell, interpret the plot.
embed_scatter = px.scatter(embeddings_df, x='component_1', y='component_2',
                           color='artist_name',
                           title = "Music Dataset Scatter Plot of Embeddings 2 PCA Components",
                           labels = {
                               'component_1' : 'Component 1',
                               'component_2' : 'Component 2',
                               'artist_name' : 'Artist Name'
                           })
embed_scatter.show()

Interpretation of the Scatter Plot of Embeddings:

- Most artists' songs have negative values in PC1.
- Beethoven songs have very low scores in PC2. Most being negative. PC1 could be a good in helping a model identify the artist Beethoven.
- Its difficult to recognize and interprete patterns in this plot as most artists score similarly in PC1 and PC2.

### Artist Centroids Plot

In [ ]:
# E) Calculate the centroids for each artist. The centroid for a given artist is comprised of the "component_1" mean and the "component_2" mean for that artist.

centroids_df = embeddings_df.groupby('artist_name').mean().reset_index()
centroids_df

          artist_name  component_1  component_2
0               ac_dc    -2.846279     2.790291
1               adele     0.067528    -0.529922
2         alicia_keys     0.636443    -0.094915
3      andrea_bocelli     1.414106    -1.846642
4       ariana_grande     4.120164     1.563161
5                bach    -0.225387    -3.477201
6           beethoven    -1.746756    -5.676132
7   bruce_springsteen    -2.765448     0.809615
8     chris_stapleton    -0.184926    -0.057711
9            coldplay    -1.670077    -0.062192
10             dr_dre     2.995631     3.300964
11      frank_sinatra    -0.879166    -0.172827
12       jason_aldean    -1.130559     0.187212
13              jay_z     0.453566     2.359379
14      john_coltrane    -1.961127    -0.642540
15        john_legend     1.239653    -0.140038
16         john_mayer    -1.975199     0.007169
17       led_zeppelin    -1.485976     0.186234
18      maggie_rogers     1.731461    -0.499905
19        miles_davis     0.604838    -0.504847
20         pink_floyd    -1.180267    -1.872167
21            rihanna     2.090919     1.315802
22       taylor_swift     1.228181     0.373217
23              tupac     1.593302     3.032945

In [ ]:
# F) Plot the centroids using a scatterplot, with "component_1" on the x axis and "component_2" on the y axis. Color on artist label. In a text cell, interpret the plot. Are there any artists who are in similar areas of the graph? Are there any artists who are more separable than others?

cent_scatter = px.scatter(centroids_df, x='component_1', y ='component_2',
                          color='artist_name',
                           title = "Scatter Plot of Centroids",
                           labels = {
                               'component_1' : 'Component 1',
                               'component_2' : 'Component 2',
                               'artist_name' : 'Artist Name'})
cent_scatter.show()

In a text cell, interpret the plot. Are there any artists who are in similar areas of the graph? Are there any artists who are more separable than others?

Interpretation of the Scatter plot of the Centroids:
- Beethoven is quite distinghuishable from the other artist. He has low negative scores (the lowest compared to other artists) for PC2 and also have low negative scores in PC1. This was seem in the plot of the embeddings as well.  
- Bach songs on average scores low in both PC1 and PC2, just as songs from Beethoven. The songs from these artists may be similar and recommending Bach to a Beethoven lover could be a good idea and vice versa.
- Ariana Grande's songs also seem to be quite seperable from he others. The mean of PC1 is very high for Ariana Grande's songs.
- Dr Dre and Rihanna are also quite distinguishable from the others with PC2 mean of their songs being very positively high. It is also high for PC1. Recommending Dr Dre songs to Rihanna lovers could be a good idea as their songs are similar on PC1 and PC2.
- The PC1 and PC2 means of songs by Miles Davis and Alicia Keys are very close. This could mean that their songs are very similar to each other. The same could be the case for Taaylor Swift and John Legend.
- AC DC is also quite distinguishable from the other artists. Their songs scored very high in PC2 and very negatively low in PC1. Bruce Springsteen scored similarly as AC DC on PC1. Their songs could similar to each other for the elements captured in PC1 and PC2.
- The other artists that cluster around zero on PC2 can be assumed to be similar in nature. However, considering that PC1 and PC2 explain only approx. 40% of the total variance in the data, there could be some missing information. Therefore some important information is missing in helping us determine how actually similar these artists and their songs are.

## Part 5 - PCA Tuning

Determine the ideal number of components to use for dimensionality reduction.

A) Loop through a range of numbers of components `n`, starting at 1, and ending at the number of total features. For each number of components:

  + Train a `PCA` model using that number of components.
  + Print the sum of the explained variance that number of components.
  + Store the sum of the explained variance, along with the corresponding number of components, in a variable so we can plot them later. Consider using a list of dictionaries and then converting it into a `pandas.DataFrame`.

B) **Explained Variance Chart**:

  + Plot a line chart of the explained variance on the y axis and the  number of components on the x axis.
  + In a text cell, interpret the chart. How many components explain 80% of the variance in the original data? How many components explain 90% of the variance?

> NOTE: the explained variance increases as the number of components increases, approaching 100% for all of the original features.

C) **Scree Plot**:

  + Plot a line chart of the eigenvalues on the y axis and the number of components on the x axis.
  + In a text cell, interpret the chart. What is the greatest number of components where the eigenvalue is greater than one? Is there an "elbow" bend in the curve?

> NOTE: the eigenvalues are given by the trained PCA model's `explained_variance_` property, for the PCA model using the maximum number of components.

> NOTE: the eigenvalues decrease as the number of components increases.

D) Based on these results, choose an **optimal number of components** to use, and write your answer in a text cell. Describe why you chose that number. Identify any other potential numbers you were considering.

### Explained Variance Plot

In [ ]:
# A) Loop through a range of numbers of components n, starting at 1, and ending at the number of total features. For each number of components:

# Train a PCA model using that number of components.
# Print the sum of the explained variance that number of components.
# Store the sum of the explained variance, along with the corresponding number of components, in a variable so we can plot them later. Consider using a list of dictionaries and then converting it into a pandas.DataFrame.

exp_var = []

for i in range(1, len(x_scaled.columns)+1):
    pca_tuning = PCA(n_components=i, random_state=21)
    embeddings_tun = pca_tuning.fit_transform(x_scaled)
    print(f"Number of components: {i}")
    print(f"    Shape of Embeddings: {embeddings_tun.shape}")
    exp_var.append({'n_components': i, 'cum_explained_variance_ratio': sum(pca_tuning.explained_variance_ratio_)})
    print(f"    Explained Variance: {sum(pca_tuning.explained_variance_).round(4)}")
    print(f"    Explained Variance Ratio: {pca_tuning.explained_variance_ratio_}")

    eigen_vals = pca_tuning.explained_variance_

Number of components: 1
    Shape of Embeddings: (1818, 1)
    Explained Variance: 8.9751
    Explained Variance Ratio: [0.21890505]
Number of components: 2
    Shape of Embeddings: (1818, 2)
    Explained Variance: 15.9862
    Explained Variance Ratio: [0.21890505 0.17100147]
Number of components: 3
    Shape of Embeddings: (1818, 3)
    Explained Variance: 19.9971
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746]
Number of components: 4
    Shape of Embeddings: (1818, 4)
    Explained Variance: 22.8575
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635]
Number of components: 5
    Shape of Embeddings: (1818, 5)
    Explained Variance: 24.7156
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186 ]
Number of components: 6
    Shape of Embeddings: (1818, 6)
    Explained Variance: 26.2895
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781]
Number of components: 7
    Shape of Embeddings: (1818, 7)
    Explained Variance: 27.5917
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046]
Number of components: 8
    Shape of Embeddings: (1818, 8)
    Explained Variance: 28.7124
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597]
Number of components: 9
    Shape of Embeddings: (1818, 9)
    Explained Variance: 29.8008
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608]
Number of components: 10
    Shape of Embeddings: (1818, 10)
    Explained Variance: 30.7798
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807]
Number of components: 11
    Shape of Embeddings: (1818, 11)
    Explained Variance: 31.7117
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791]
Number of components: 12
    Shape of Embeddings: (1818, 12)
    Explained Variance: 32.5861
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868]
Number of components: 13
    Shape of Embeddings: (1818, 13)
    Explained Variance: 33.297
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822]
Number of components: 14
    Shape of Embeddings: (1818, 14)
    Explained Variance: 33.9357
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851]
Number of components: 15
    Shape of Embeddings: (1818, 15)
    Explained Variance: 34.5324
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542 ]
Number of components: 16
    Shape of Embeddings: (1818, 16)
    Explained Variance: 35.1103
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467]
Number of components: 17
    Shape of Embeddings: (1818, 17)
    Explained Variance: 35.6692
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017]
Number of components: 18
    Shape of Embeddings: (1818, 18)
    Explained Variance: 36.1825
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985]
Number of components: 19
    Shape of Embeddings: (1818, 19)
    Explained Variance: 36.638
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019]
Number of components: 20
    Shape of Embeddings: (1818, 20)
    Explained Variance: 37.0459
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481 ]
Number of components: 21
    Shape of Embeddings: (1818, 21)
    Explained Variance: 37.4384
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446]
Number of components: 22
    Shape of Embeddings: (1818, 22)
    Explained Variance: 37.8184
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716]
Number of components: 23
    Shape of Embeddings: (1818, 23)
    Explained Variance: 38.1561
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819]
Number of components: 24
    Shape of Embeddings: (1818, 24)
    Explained Variance: 38.457
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809]
Number of components: 25
    Shape of Embeddings: (1818, 25)
    Explained Variance: 38.7524
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537]
Number of components: 26
    Shape of Embeddings: (1818, 26)
    Explained Variance: 39.0083
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081]
Number of components: 27
    Shape of Embeddings: (1818, 27)
    Explained Variance: 39.2595
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707]
Number of components: 28
    Shape of Embeddings: (1818, 28)
    Explained Variance: 39.497
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174]
Number of components: 29
    Shape of Embeddings: (1818, 29)
    Explained Variance: 39.7137
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853 ]
Number of components: 30
    Shape of Embeddings: (1818, 30)
    Explained Variance: 39.9204
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261]
Number of components: 31
    Shape of Embeddings: (1818, 31)
    Explained Variance: 40.1185
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057]
Number of components: 32
    Shape of Embeddings: (1818, 32)
    Explained Variance: 40.3083
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072]
Number of components: 33
    Shape of Embeddings: (1818, 33)
    Explained Variance: 40.4898
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629]
Number of components: 34
    Shape of Embeddings: (1818, 34)
    Explained Variance: 40.6387
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077]
Number of components: 35
    Shape of Embeddings: (1818, 35)
    Explained Variance: 40.7495
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077 0.0027031 ]
Number of components: 36
    Shape of Embeddings: (1818, 36)
    Explained Variance: 40.8381
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077 0.0027031  0.0021607 ]
Number of components: 37
    Shape of Embeddings: (1818, 37)
    Explained Variance: 40.9026
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077 0.0027031  0.0021607
 0.0015739 ]
Number of components: 38
    Shape of Embeddings: (1818, 38)
    Explained Variance: 40.9488
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077 0.0027031  0.0021607
 0.0015739  0.0011267 ]
Number of components: 39
    Shape of Embeddings: (1818, 39)
    Explained Variance: 40.9849
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077 0.0027031  0.0021607
 0.0015739  0.0011267  0.00088034]
Number of components: 40
    Shape of Embeddings: (1818, 40)
    Explained Variance: 40.9964
    Explained Variance Ratio: [0.21890505 0.17100147 0.09782746 0.06976635 0.0453186  0.03838781
 0.03176046 0.02733597 0.02654608 0.02387807 0.02272791 0.02132868
 0.01733822 0.01557851 0.0145542  0.01409467 0.01363017 0.01251985
 0.01111019 0.0099481  0.00957446 0.00926716 0.00823819 0.00733809
 0.00720537 0.00624081 0.00612707 0.00579174 0.0052853  0.00504261
 0.00483057 0.00463072 0.00442629 0.00363077 0.0027031  0.0021607
 0.0015739  0.0011267  0.00088034 0.0002802 ]
Number of components: 41
    Shape of Embeddings: (1818, 41)
    Explained Variance: 41.0
    Explained Variance Ratio: [2.18905054e-01 1.71001473e-01 9.78274627e-02 6.97663509e-02
 4.53186036e-02 3.83878105e-02 3.17604605e-02 2.73359660e-02
 2.65460828e-02 2.38780708e-02 2.27279148e-02 2.13286761e-02
 1.73382187e-02 1.55785128e-02 1.45541965e-02 1.40946743e-02
 1.36301712e-02 1.25198453e-02 1.11101940e-02 9.94809866e-03
 9.57446107e-03 9.26716347e-03 8.23818902e-03 7.33808811e-03
 7.20537352e-03 6.24080579e-03 6.12706911e-03 5.79174279e-03
 5.28529569e-03 5.04261209e-03 4.83056653e-03 4.63071952e-03
 4.42629491e-03 3.63076714e-03 2.70309829e-03 2.16070149e-03
 1.57390053e-03 1.12669553e-03 8.80337478e-04 2.80197995e-04
 8.80826197e-05]

In [ ]:
explained_var_df = pd.DataFrame(exp_var)
explained_var_df

    n_components  cum_explained_variance_ratio
0              1                      0.218905
1              2                      0.389907
2              3                      0.487734
3              4                      0.557500
4              5                      0.602819
5              6                      0.641207
6              7                      0.672967
7              8                      0.700303
8              9                      0.726849
9             10                      0.750727
10            11                      0.773455
11            12                      0.794784
12            13                      0.812122
13            14                      0.827701
14            15                      0.842255
15            16                      0.856350
16            17                      0.869980
17            18                      0.882500
18            19                      0.893610
19            20                      0.903558
20            21                      0.913132
21            22                      0.922399
22            23                      0.930638
23            24                      0.937976
24            25                      0.945181
25            26                      0.951422
26            27                      0.957549
27            28                      0.963341
28            29                      0.968626
29            30                      0.973669
30            31                      0.978499
31            32                      0.983130
32            33                      0.987556
33            34                      0.991187
34            35                      0.993890
35            36                      0.996051
36            37                      0.997625
37            38                      0.998751
38            39                      0.999632
39            40                      0.999912
40            41                      1.000000

In [ ]:
# B) Explained Variance Chart:
# Plot a line chart of the explained variance on the y axis and the number of components on the x axis.

line_exp_var = px.line(explained_var_df, x='n_components', y='cum_explained_variance_ratio',
                       title='Line Chart of Cummulative Explained Variance Ratio for Music Dataset',
                       markers = True,
                       labels = {
                           'cum_explained_variance_ratio' : 'Cummulative Explained Variance Ratio',
                           'n_components' : 'Number of Principal Components'
                       })
line_exp_var.show()

In a text cell, interpret the chart. How many components explain 80% of the variance in the original data? How many components explain 90% of the variance?
NOTE: the explained variance increases as the number of components increases, approaching 100% for all of the original features.

Interpretation of Explained Variance Plot:

- The line graph of the cummulative explained variance plot shows the increase in the proportion of explained variance with each increase in PCA components.
- Just as we saw above, 2 components explains approximately 40% of the data, this is very low.
- The line graph shows us that 12 components explains 80% of the variance of the original data. This is incredible considering the original data has 41 features.
- The line graph also shows that if we use 20 components, 90% of the variance from the original data would be explained. Once again, this is very impressive as we are able to understand and make interpretations about the original data by using about half of the original features.

### Scree Plot

In [ ]:
# C) Scree Plot:
# Plot a line chart of the eigenvalues on the y axis and the number of components on the x axis.
line_eigen = px.line(x=list(range(1,len(eigen_vals)+1)), y=eigen_vals,
                       title='PCA Scree Plot for Music Dataset',
                       markers = True,
                       labels = {
                           'y' : 'Eigen Value',
                           'x' : 'Number of Principal Components'
                       })
line_eigen.add_hline(y=1, line_width=1, line_dash="dot", line_color="red", )
line_eigen.show()

In a text cell, interpret the chart. What is the greatest number of components where the eigenvalue is greater than one? Is there an "elbow" bend in the curve?
NOTE: the eigenvalues are given by the trained PCA model's explained_variance_ property, for the PCA model using the maximum number of components.
D) Based on these results, choose an optimal number of components to use, and write your answer in a text cell. Describe why you chose that number. Identify any other potential numbers you were considering.

NOTE: the eigenvalues decrease as the number of components increases.

Interpretation of Scree Plot:
- Based on the Kaiser Rule, the best number of principal components that would accurately represent the original Music dataset would the first 10.
- Based on the Scree Plot for the Music dataset, the elbow of the plot seems to be at 13 components and its seems to level off from there. This suggests that we should keep 12 components from the PCA.
- The Scree Plot also seems to show another elbow at 11 components suggesting that 10 components should be retained. The cumulative explained variance ratio at 10 components is 75%. This is a good proportion of variance. This also agrees with the Kaiser rule which suggests that we only retain the first 10 compoents.

Therefore, considering that the scree plot levels out after 12 components, the eigen value for 12 is close 1, and that the first 12 components explain 80% of the variance in the original data, I believe the optimal number of components is 12.

### Optimal Number of Components

Answer: 12

## Part 6 - Artist Classification (Reduced Feature Embeddings)

Perform dimensionality reduction on the reduced audio feature embeddings.


A) Reduced Embeddings:

  + Using the number of features you identified in Part 5D, train a `PCA` model on the scaled data.
  + Print the sum of explained variance when using this number of components.
  + Store the embeddings in a `pandas.DataFrame`, using appropriate column names and index values. Add / marge the artist name labels back in for charting later.

B) Classification on the Embeddings:

  + Perform a train/test split using the embeddings as the features.
  + Train a `LogisticRegression` model using the embeddings training data.
  + Evaluate the model using a classification report and confusion matrix.
  + In a text cell, interpret the results. How well did the model do? Which artists have the highest F1 scores, and which have the lowest? Which pairs of artists are most confused with eachother?

C) Results Comparison:

  + In a text cell, compare the classification results from Part 3D using all features, against the classification results from Part 5D using the reduced embeddings as features. What does this tell us about the dimensionality reduction process?

In [ ]:
# A) Reduced Embeddings:
# Using the number of features you identified in Part 5D, train a PCA model on the scaled data.
# Print the sum of explained variance when using this number of components.
pca = PCA(n_components=12, random_state=21)

embeddings = pca.fit_transform(x_scaled)
print(f"Shape of the Embeddings: {embeddings.shape}")
print(f"Sum of Explained Variance when 12 components are retained: {sum(pca.explained_variance_)}")
print(f"Sum of the Proportion of Explained Variance when 12 components are retained: {sum(pca.explained_variance_ratio_)}")

Shape of the Embeddings: (1818, 12)
Sum of Explained Variance when 12 components are retained: 32.58614095863338
Sum of the Proportion of Explained Variance when 12 components are retained: 0.7947839258203263

In [ ]:
# Store the embeddings in a pandas.DataFrame, using appropriate column names and index values. Add / marge the artist name labels back in for charting later.
component_names = [f"component_{i+1}" for i in range(12)]

classif_embeddings_df = pd.DataFrame(embeddings, columns = component_names)
classif_embeddings_df

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,component_11,component_12
0,2.202601,0.745840,-3.912757,1.350484,2.441615,-0.167053,0.145839,-0.421139,-1.587666,-0.160821,1.492257,1.568632
1,2.491992,0.020364,-1.951810,0.211439,2.125171,-0.958780,-0.875155,0.249958,-0.861300,-0.310641,0.963366,-0.139616
2,-1.130122,0.444325,-1.284325,0.489278,1.313492,-0.937059,-0.179890,0.581062,-0.619311,0.023836,1.090626,0.573718
3,0.230034,0.480557,-0.921548,0.009588,1.649616,-1.355418,0.037901,-0.057676,-0.644679,-0.294023,1.039422,0.535166
4,-1.256497,-0.141737,0.925641,1.691576,0.014110,1.229480,-1.272437,1.479420,-0.399058,0.562210,3.004974,0.454971
...,...,...,...,...,...,...,...,...,...,...,...,...
1813,-4.049552,4.266147,-1.475179,-2.260594,0.431776,0.936527,1.040009,1.264727,1.558897,-0.110409,-0.333631,-0.732117
1814,-0.139328,1.263042,-1.349360,-1.760777,-0.209011,1.410555,-0.014386,0.530275,2.736480,0.240519,1.178428,1.199285
1815,-0.180542,2.521628,-2.242287,-2.900636,0.171609,2.012492,1.185284,1.773023,-0.184411,-0.312937,0.740261,-0.017616
1816,-4.761295,4.381796,-1.443139,-1.857723,0.155764,1.007041,1.018307,1.331608,1.436497,-0.088256,-0.217267,-0.226243
1817,3.567767,0.086380,-7.036393,3.186006,-1.761740,0.903911,3.563868,-3.001923,4.573968,0.433814,2.841106,2.018433

In [ ]:
# B) Classification on the Embeddings:
# Perform a train/test split using the embeddings as the features.
x_train, x_test, y_train, y_test = train_test_split(classif_embeddings_df, y,
                                                    test_size=0.2,
                                                    random_state=21)
print("TRAIN:", x_train.shape, y_train.shape)
print("TEST:", x_test.shape, y_test.shape)

TRAIN: (1454, 12) (1454, 1)
TEST: (364, 12) (364, 1)

In [ ]:
# Train a LogisticRegression model using the embeddings training data.
model = LogisticRegression(random_state=21)
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

LogisticRegression(random_state=21)

In [ ]:
# Evaluate the model using a classification report and confusion matrix.
#predict test set
y_pred = model.predict(x_test)
#print classification report
print(classification_report(y_test, y_pred))

                   precision    recall  f1-score   support

            ac_dc       0.67      0.80      0.73        15
            adele       0.61      0.65      0.63        17
      alicia_keys       0.29      0.33      0.31         6
   andrea_bocelli       0.82      0.82      0.82        11
    ariana_grande       0.71      0.80      0.75        15
             bach       0.59      0.72      0.65        18
        beethoven       0.71      0.75      0.73        16
bruce_springsteen       0.54      0.58      0.56        24
  chris_stapleton       0.67      0.71      0.69        14
         coldplay       0.50      0.43      0.46        21
           dr_dre       0.73      0.62      0.67        13
    frank_sinatra       0.50      0.20      0.29         5
     jason_aldean       0.43      0.33      0.38         9
            jay_z       0.75      0.67      0.71        18
    john_coltrane       0.70      0.86      0.78        22
      john_legend       0.50      0.46      0.48        13
       john_mayer       0.67      0.71      0.69        14
     led_zeppelin       0.31      0.50      0.38        10
    maggie_rogers       0.56      0.33      0.42        15
      miles_davis       0.69      0.67      0.68        30
       pink_floyd       0.45      0.42      0.43        12
          rihanna       0.20      0.12      0.15         8
     taylor_swift       0.55      0.46      0.50        26
            tupac       0.69      0.75      0.72        12

         accuracy                           0.60       364
        macro avg       0.58      0.57      0.57       364
     weighted avg       0.60      0.60      0.60       364

In [ ]:
# Display a confusion matrix
plot_confusion_matrix(y_test, y_pred, height=900, title="Confusion Matrix for Clasification of PCA Music Dataset using 12 Components")

In a text cell, interpret the results. How well did the model do? Which artists have the highest F1 scores, and which have the lowest? Which pairs of artists are most confused with eachother?

Classification Report Interpretation:

- Accuracy - the model has an accuracy of 0.60. This indicates that the model did well as it predicted the correct artist for 60% of the songs in the test set correctly.
- This accuracy score is still significantly better than the 6.49% random chance guess. This makes this model still very good despite using less than half of the columns.
- Andrea Bocelli, John Coltrane and Ariana Grande have the highest f1 scores of 0.82, 0.78 and 0.75 respectively. This means that for these artists the model is doing a great job at correctly classifiying songs with their actual artists and it also does a great job at not misclassifying these artists songs as other artists'.
- Rihanna, Frank Sinatra and Alicia Keys have the lowest f1 scores of 0.14, 0.29 and 0.31 respectively. This means that the model doesn't do a great job of distinguishing between their songs and others well enough to correctly classify their songs. Additionally, the model doesn't do a great job at not misclassfying their songs with the songs of other artists.

Confusion Matrix Interpretation:

The three pairs of artists who were most confued with each other were:

1. Bruce Springsteen and Cold Play - the model inaccurately predicted 5 Cold Play songs as Bruce Springsteen songs.
2. Maggie Rogers and Adele - the model incorrectly predicted 4 Maggie Roggers songs as Adele songs.
3. Miles Davis and John Coltrane - the model incaccurately predicted 4 Miles Davis songs as John Coltrane's.

C) Results Comparison:
In a text cell, compare the classification results from Part 3D using all features, against the classification results from Part 5D using the reduced embeddings as features. What does this tell us about the dimensionality reduction process?

Results Comparison:

- The initial classification model for predicting the artist based on a track using all features of the music dataset has an accuracy score of 75%. The reduced embeddings classification model has an accuracy score of 60%. The reduced embeddings model used 12 components compared to the initial model's 41 features and was still able to correctly predict 60% of the artists correctly. Whilst the model did slightly worse by 15%, it used less than half of the original features making dimensinality reduction an impressive and useful tool. It means that PCA truly retain alot of the importance information contained in the original data. The information that it was able to retain in just 12 components was so valuable that the classification model was still able to recognize patterns and relationships in the embeddings and make accurate predictions.
- The f1 scores for the embeddings model decreased compared to the initial model which used all the features. The artists with the highest and lowest f1 scores differed from the initial model.
- The artists with the most confusion also slightly differed in the embeddings model compared to the initial model. However, it is still impressive that with few components the model was still confused by Miles Davis and John Coltrane's music. This could suggest that their music is truly very similar and even when their songs are compared accross 44 features, their songs are still hard to distinguish from each other.


Overall, the model that used dimensionality reduction still performed very well in comparison to the initial model. PCA was able to capture enough information about the entire dataset in just 12 components rather than 41 and still produce good results in a classification model. Very impressive.